### PR TITLE
add some openapi, update unit test and add orchestration field interface

### PR DESCRIPTION
**Pull request by ibfru**

### CODE REVIEW

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>静态代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/10/10_静态代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>98.4
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/10/10_测试用例覆盖率检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/10/10_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/10/10_代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/10/10_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/4d0001dbe76242f99bd0cf1e9a61917b/6933cfbdaf2847c8be16ae6526a942f4">点击跳转</a></td>
</tr>
</table>

**Review by GeorgeCao-hw — COMMENTED** [review]
/lgtm
ut code and  test data.

**Review by GeorgeCao-hw — APPROVED** [review]
/lgtm

**Pull request merged**
