### PR TITLE
add a  openapi and fix openapi error [page result wrong, reqeust arguments not a pointer], add the pointer check

### PR DESCRIPTION
**Pull request by ibfru**

### CODE REVIEW

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse">
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>97.6
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_DT覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/4d0001dbe76242f99bd0cf1e9a61917b/a25e1bc463c0488d807d6803686fbd9f">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse">
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>静态代码检查</td>
    <td>&#128346;</td>
    <td>任务失败, 请重试</td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>97.6
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_测试用例覆盖率检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/4d0001dbe76242f99bd0cf1e9a61917b/7fb792ce46ae4380861cc17443df27f2">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
<table style="border-collapse: collapse">
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>静态代码检查</td>
    <td>&#10060;</td>
    <td>任务失败, 请重试</td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>97.6
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_测试用例覆盖率检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>代码漏洞扫描</td>
    <td>&#None;</td>
    <td></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#None;</td>
    <td></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/4d0001dbe76242f99bd0cf1e9a61917b/bd3b0f49fea34ccc89ca9b46bc934f77">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
<table style="border-collapse: collapse">
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>静态代码检查</td>
    <td>&#10060;</td>
    <td>任务失败, 请重试</td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>97.6
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_测试用例覆盖率检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/4d0001dbe76242f99bd0cf1e9a61917b/7542c532ecda4d72bb6fc17e956db57a">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
<table style="border-collapse: collapse">
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>静态代码检查</td>
    <td>&#10060;</td>
    <td>任务失败, 请重试</td>
</tr>

<tr>
    <td>测试用例覆盖率检查</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_测试用例覆盖率检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/4d0001dbe76242f99bd0cf1e9a61917b/492225e8e48e4da19684c0beac35bebb">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
<table style="border-collapse: collapse">
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>静态代码检查</td>
    <td>&#10060;</td>
    <td>任务失败, 请重试</td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>97.6
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_测试用例覆盖率检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/4d0001dbe76242f99bd0cf1e9a61917b/ad2c34eb699847499395957c8b570ec4">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse">
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>静态代码检查</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_静态代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>93.8
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_测试用例覆盖率检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/4d0001dbe76242f99bd0cf1e9a61917b/24e356b32cb941919ccd85b9ec88c8c1">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse">
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>静态代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_静态代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>85.6
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_测试用例覆盖率检查.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/go-gitcode/9/9_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/4d0001dbe76242f99bd0cf1e9a61917b/6ab6fb07242f4eb28473134b4edd6ba9">点击跳转</a></td>
</tr>
</table>

**Review by GeorgeCao-hw — APPROVED** [review]
/lgtm

**Pull request merged**
